# Generated by Django 6.0.6 on 2026-06-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillscategory',
            options={'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
    ]
