# Generated by Django 6.0.5 on 2026-05-30 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(related_name='projects', to='users.skills'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['min_price'], name='projects_pr_min_pri_155532_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['max_price'], name='projects_pr_max_pri_cd5977_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['min_price', 'max_price'], name='projects_pr_min_pri_1b4663_idx'),
        ),
    ]
