# Generated by Django 6.0.6 on 2026-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_freelancer_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED')], db_index=True, default='open', max_length=16),
        ),
    ]
