# Generated by Django 6.0.6 on 2026-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
