# Generated by Django 6.0.6 on 2026-06-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_max_price_alter_project_min_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_min_pri_155532_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_max_pri_cd5977_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_min_pri_1b4663_idx',
        ),
    ]
