# Generated by Django 6.0.6 on 2026-06-14 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_projects_pr_min_pri_155532_idx_and_more'),
        ('users', '0010_emailverification_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('max_price__gte', models.F('min_price'))), name='project_price_valid'),
        ),
    ]
