# Generated by Django 6.0.6 on 2026-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
