# Generated by Django 6.0.6 on 2026-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
