import { useState } from 'react'
import { LanguageContext } from './language'

const translations = {
  en: {
    browse: 'Browse projects', dashboard: 'Dashboard', login: 'Log in', logout: 'Log out',
    started: 'Get started', welcome: 'Welcome back', loginTitle: 'Log in to Freeform',
    loginText: 'Continue to your projects and proposals.', username: 'Username', password: 'Password',
    logging: 'Logging in…', newHere: 'New here?', createAccount: 'Create an account',
    join: 'Join Freeform', registerTitle: 'Create your account', registerText: 'Choose how you want to work on the marketplace.',
    freelancer: 'Freelancer', client: 'Client', email: 'Email', country: 'Country ID',
    countryHint: 'Enter the integer ID configured for your country in the API.', confirm: 'Confirm password',
    selectCountry: 'Select a country', loadingCountries: 'Loading countries…', countriesError: 'Countries could not be loaded.',
    creating: 'Creating account…', create: 'Create account', existing: 'Already have an account?',
    verifyTitle: 'Verify your email', verifyText: 'Enter the six-digit code sent to your email address.',
    verifying: 'Verifying…', verify: 'Verify email', continue: 'Continue', resend: 'Resend code',
    openWork: 'Open opportunities', findProject: 'Find your next project', available: 'available',
    searchProjects: 'Search projects…', finding: 'Finding projects', loadProjectsError: 'Projects could not be loaded',
    retry: 'Try again', previous: 'Previous', next: 'Next', noMatches: 'No matching projects',
    noMatchesText: 'Try a broader search or check back when new work is posted.', postedBy: 'Posted by', view: 'View',
    loadingProject: 'Loading project', unavailable: 'Project unavailable', backProjects: 'Back to projects',
    aboutProject: 'About the project', skills: 'Skills', proposals: 'Proposals', visible: 'visible',
    privateProposals: 'Proposal details are private unless the API includes bids with this project.',
    projectBudget: 'Project budget', assignedTo: 'Assigned to', placeBid: 'Place a bid',
    bidHint: 'Make your proposal specific and concise.', yourPrice: 'Your price', proposal: 'Proposal',
    proposalPlaceholder: 'How would you approach this project?', submitting: 'Submitting…', submitProposal: 'Submit proposal',
    loginToBidText: 'Log in as a freelancer to send a proposal.', loginToBid: 'Log in to bid',
    clientWorkspace: 'Client workspace', yourProjects: 'Your projects', clientIntro: 'Track work and choose the right proposal.',
    hideForm: 'Hide form', newProject: 'New project', loadingProjects: 'Loading your projects',
    dashboardError: 'Dashboard could not be loaded', project: 'Project', budget: 'Budget',
    noProjects: 'No projects yet', noProjectsText: 'Create your first project to start receiving proposals.',
    createProject: 'Create a project', createIntro: 'Share a clear brief and realistic budget.', close: 'Close',
    projectTitle: 'Project title', projectTitleExample: 'e.g. Build a React analytics dashboard', description: 'Description',
    descriptionPlaceholder: 'Describe the outcome, requirements, and expected delivery…', minBudget: 'Minimum budget',
    maxBudget: 'Maximum budget', skillIds: 'Required skill IDs', skillIdsHint: 'Comma-separated IDs from the API skill catalog.',
    publishing: 'Publishing…', publish: 'Publish project', acceptBid: 'Accept a bid',
    acceptHint: 'Enter the bid ID from the proposal you want to accept.', accepting: 'Accepting…', confirmAction: 'Confirm', cancel: 'Cancel',
    freelancerWorkspace: 'Freelancer workspace', yourProposals: 'Your proposals',
    freelancerIntro: 'Follow every opportunity from proposal to decision.', findProjects: 'Find projects',
    totalBids: 'Total bids', pending: 'Pending', accepted: 'Accepted', loadingProposals: 'Loading your proposals',
    proposalsError: 'Proposals could not be loaded', bid: 'Bid', noProposals: 'No proposals yet',
    noProposalsText: 'Browse open projects and send a thoughtful first proposal.', footer: 'Independent work, professionally matched.',
    heroBadge: 'New projects added daily', heroTitle: 'Where ambitious work finds exceptional talent.',
    heroText: 'A focused marketplace for clients with important work and freelancers who know how to deliver it.',
    explore: 'Explore projects', postProject: 'Post a project', clearBudgets: 'Clear budgets',
    directProposals: 'Direct proposals', noClutter: 'No clutter', momentum: 'Designed for momentum',
    everything: 'Everything you need. Nothing in the way.', workflow: 'A better workflow',
    nextCollab: 'Your next great collaboration starts here.', browseOpportunities: 'Browse opportunities',
  },
  uz: {
    browse: 'Loyihalarni ko‘rish', dashboard: 'Boshqaruv paneli', login: 'Kirish', logout: 'Chiqish',
    started: 'Boshlash', welcome: 'Xush kelibsiz', loginTitle: 'Freeform’ga kiring',
    loginText: 'Loyihalar va takliflaringizga o‘ting.', username: 'Foydalanuvchi nomi', password: 'Parol',
    logging: 'Kirilmoqda…', newHere: 'Yangi foydalanuvchimisiz?', createAccount: 'Hisob yaratish',
    join: 'Freeform’ga qo‘shiling', registerTitle: 'Hisobingizni yarating', registerText: 'Platformada qanday ishlashingizni tanlang.',
    freelancer: 'Frilanser', client: 'Mijoz', email: 'Elektron pochta', country: 'Mamlakat ID',
    countryHint: 'API’da sozlangan mamlakat raqamini kiriting.', confirm: 'Parolni tasdiqlang',
    selectCountry: 'Mamlakatni tanlang', loadingCountries: 'Mamlakatlar yuklanmoqda…', countriesError: 'Mamlakatlarni yuklab bo‘lmadi.',
    creating: 'Hisob yaratilmoqda…', create: 'Hisob yaratish', existing: 'Hisobingiz bormi?',
    verifyTitle: 'Pochtangizni tasdiqlang', verifyText: 'Elektron pochtangizga yuborilgan olti xonali kodni kiriting.',
    verifying: 'Tekshirilmoqda…', verify: 'Pochtani tasdiqlash', continue: 'Davom etish', resend: 'Kodni qayta yuborish',
    openWork: 'Ochiq imkoniyatlar', findProject: 'Keyingi loyihangizni toping', available: 'mavjud',
    searchProjects: 'Loyihalarni qidirish…', finding: 'Loyihalar qidirilmoqda', loadProjectsError: 'Loyihalarni yuklab bo‘lmadi',
    retry: 'Qayta urinish', previous: 'Oldingi', next: 'Keyingi', noMatches: 'Mos loyiha topilmadi',
    noMatchesText: 'Kengroq qidiring yoki yangi loyihalarni kuting.', postedBy: 'Joylashtirgan', view: 'Ko‘rish',
    loadingProject: 'Loyiha yuklanmoqda', unavailable: 'Loyiha mavjud emas', backProjects: 'Loyihalarga qaytish',
    aboutProject: 'Loyiha haqida', skills: 'Ko‘nikmalar', proposals: 'Takliflar', visible: 'ko‘rinadi',
    privateProposals: 'API loyiha bilan takliflarni bermasa, taklif tafsilotlari yopiq bo‘ladi.',
    projectBudget: 'Loyiha budjeti', assignedTo: 'Biriktirilgan', placeBid: 'Taklif berish',
    bidHint: 'Taklifingiz aniq va qisqa bo‘lsin.', yourPrice: 'Narxingiz', proposal: 'Taklif',
    proposalPlaceholder: 'Bu loyihaga qanday yondashasiz?', submitting: 'Yuborilmoqda…', submitProposal: 'Taklifni yuborish',
    loginToBidText: 'Taklif yuborish uchun frilanser sifatida kiring.', loginToBid: 'Taklif uchun kirish',
    clientWorkspace: 'Mijoz paneli', yourProjects: 'Loyihalaringiz', clientIntro: 'Ishlarni kuzating va mos taklifni tanlang.',
    hideForm: 'Formani yashirish', newProject: 'Yangi loyiha', loadingProjects: 'Loyihalar yuklanmoqda',
    dashboardError: 'Panelni yuklab bo‘lmadi', project: 'Loyiha', budget: 'Budjet',
    noProjects: 'Hali loyiha yo‘q', noProjectsText: 'Takliflar olish uchun birinchi loyihangizni yarating.',
    createProject: 'Loyiha yaratish', createIntro: 'Aniq topshiriq va real budjet kiriting.', close: 'Yopish',
    projectTitle: 'Loyiha nomi', projectTitleExample: 'masalan, React analitika paneli', description: 'Tavsif',
    descriptionPlaceholder: 'Natija, talablar va muddatni tasvirlang…', minBudget: 'Minimal budjet',
    maxBudget: 'Maksimal budjet', skillIds: 'Kerakli ko‘nikma IDlari', skillIdsHint: 'API katalogidagi IDlarni vergul bilan ajrating.',
    publishing: 'Nashr qilinmoqda…', publish: 'Loyihani nashr qilish', acceptBid: 'Taklifni qabul qilish',
    acceptHint: 'Qabul qilmoqchi bo‘lgan taklif ID sini kiriting.', accepting: 'Qabul qilinmoqda…', confirmAction: 'Tasdiqlash', cancel: 'Bekor qilish',
    freelancerWorkspace: 'Frilanser paneli', yourProposals: 'Takliflaringiz',
    freelancerIntro: 'Har bir taklif holatini kuzating.', findProjects: 'Loyihalarni topish',
    totalBids: 'Jami takliflar', pending: 'Kutilmoqda', accepted: 'Qabul qilingan', loadingProposals: 'Takliflar yuklanmoqda',
    proposalsError: 'Takliflarni yuklab bo‘lmadi', bid: 'Taklif', noProposals: 'Hali taklif yo‘q',
    noProposalsText: 'Ochiq loyihalarni ko‘rib, birinchi taklifingizni yuboring.', footer: 'Mustaqil ish, professional hamkorlik.',
    heroBadge: 'Har kuni yangi loyihalar', heroTitle: 'Katta maqsadlar kuchli mutaxassislarni topadigan joy.',
    heroText: 'Muhim loyihali mijozlar va uni bajaradigan frilanserlar uchun qulay platforma.',
    explore: 'Loyihalarni ko‘rish', postProject: 'Loyiha joylash', clearBudgets: 'Aniq budjetlar',
    directProposals: 'Bevosita takliflar', noClutter: 'Ortiqcha narsalarsiz', momentum: 'Tezlik uchun yaratilgan',
    everything: 'Kerakli hamma narsa. Ortiqcha hech narsa.', workflow: 'Yaxshiroq ish jarayoni',
    nextCollab: 'Keyingi ajoyib hamkorligingiz shu yerdan boshlanadi.', browseOpportunities: 'Imkoniyatlarni ko‘rish',
  },
  ru: {
    browse: 'Смотреть проекты', dashboard: 'Панель управления', login: 'Войти', logout: 'Выйти',
    started: 'Начать', welcome: 'С возвращением', loginTitle: 'Войти в Freeform',
    loginText: 'Перейдите к своим проектам и предложениям.', username: 'Имя пользователя', password: 'Пароль',
    logging: 'Вход…', newHere: 'Впервые здесь?', createAccount: 'Создать аккаунт',
    join: 'Присоединиться к Freeform', registerTitle: 'Создайте аккаунт', registerText: 'Выберите, как вы хотите работать на платформе.',
    freelancer: 'Фрилансер', client: 'Клиент', email: 'Электронная почта', country: 'ID страны',
    countryHint: 'Введите числовой ID страны, настроенный в API.', confirm: 'Подтвердите пароль',
    selectCountry: 'Выберите страну', loadingCountries: 'Загрузка стран…', countriesError: 'Не удалось загрузить страны.',
    creating: 'Создание аккаунта…', create: 'Создать аккаунт', existing: 'Уже есть аккаунт?',
    verifyTitle: 'Подтвердите почту', verifyText: 'Введите шестизначный код, отправленный на вашу почту.',
    verifying: 'Проверка…', verify: 'Подтвердить почту', continue: 'Продолжить', resend: 'Отправить код снова',
    openWork: 'Открытые возможности', findProject: 'Найдите следующий проект', available: 'доступно',
    searchProjects: 'Поиск проектов…', finding: 'Поиск проектов', loadProjectsError: 'Не удалось загрузить проекты',
    retry: 'Повторить', previous: 'Назад', next: 'Далее', noMatches: 'Подходящих проектов нет',
    noMatchesText: 'Попробуйте расширить поиск или зайдите позже.', postedBy: 'Опубликовал', view: 'Открыть',
    loadingProject: 'Загрузка проекта', unavailable: 'Проект недоступен', backProjects: 'Назад к проектам',
    aboutProject: 'О проекте', skills: 'Навыки', proposals: 'Предложения', visible: 'видно',
    privateProposals: 'Детали предложений скрыты, если API не возвращает их вместе с проектом.',
    projectBudget: 'Бюджет проекта', assignedTo: 'Исполнитель', placeBid: 'Оставить заявку',
    bidHint: 'Сделайте предложение конкретным и кратким.', yourPrice: 'Ваша цена', proposal: 'Предложение',
    proposalPlaceholder: 'Как вы подойдёте к этому проекту?', submitting: 'Отправка…', submitProposal: 'Отправить предложение',
    loginToBidText: 'Войдите как фрилансер, чтобы отправить предложение.', loginToBid: 'Войти для заявки',
    clientWorkspace: 'Кабинет клиента', yourProjects: 'Ваши проекты', clientIntro: 'Следите за работой и выбирайте лучшее предложение.',
    hideForm: 'Скрыть форму', newProject: 'Новый проект', loadingProjects: 'Загрузка проектов',
    dashboardError: 'Не удалось загрузить панель', project: 'Проект', budget: 'Бюджет',
    noProjects: 'Проектов пока нет', noProjectsText: 'Создайте первый проект, чтобы получать предложения.',
    createProject: 'Создать проект', createIntro: 'Опишите задачу и укажите реалистичный бюджет.', close: 'Закрыть',
    projectTitle: 'Название проекта', projectTitleExample: 'например, панель аналитики на React', description: 'Описание',
    descriptionPlaceholder: 'Опишите результат, требования и сроки…', minBudget: 'Минимальный бюджет',
    maxBudget: 'Максимальный бюджет', skillIds: 'ID нужных навыков', skillIdsHint: 'ID из каталога API через запятую.',
    publishing: 'Публикация…', publish: 'Опубликовать проект', acceptBid: 'Принять предложение',
    acceptHint: 'Введите ID предложения, которое хотите принять.', accepting: 'Принятие…', confirmAction: 'Подтвердить', cancel: 'Отмена',
    freelancerWorkspace: 'Кабинет фрилансера', yourProposals: 'Ваши предложения',
    freelancerIntro: 'Следите за каждой возможностью от заявки до решения.', findProjects: 'Найти проекты',
    totalBids: 'Всего заявок', pending: 'Ожидают', accepted: 'Приняты', loadingProposals: 'Загрузка предложений',
    proposalsError: 'Не удалось загрузить предложения', bid: 'Заявка', noProposals: 'Предложений пока нет',
    noProposalsText: 'Просмотрите проекты и отправьте первое предложение.', footer: 'Независимая работа, профессиональный подбор.',
    heroBadge: 'Новые проекты каждый день', heroTitle: 'Где амбициозные задачи находят сильных специалистов.',
    heroText: 'Сфокусированная площадка для клиентов с важными задачами и фрилансеров, которые умеют их решать.',
    explore: 'Смотреть проекты', postProject: 'Разместить проект', clearBudgets: 'Понятные бюджеты',
    directProposals: 'Прямые предложения', noClutter: 'Ничего лишнего', momentum: 'Создано для движения',
    everything: 'Всё необходимое. Ничего лишнего.', workflow: 'Удобный процесс',
    nextCollab: 'Ваше следующее отличное сотрудничество начинается здесь.', browseOpportunities: 'Смотреть возможности',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('language') || 'en')
  function setLanguage(value) {
    localStorage.setItem('language', value)
    setLanguageState(value)
  }
  const t = (key) => translations[language]?.[key] || translations.en[key] || key
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}
