# Generated by Django 5.2.5 on 2026-05-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
