# Generated by Django 6.0.6 on 2026-06-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_alter_bid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='is_acctepted',
            new_name='is_accepted',
        ),
    ]
