# Generated by Django 6.0.6 on 2026-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_rename_is_acctepted_bid_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
