# Generated by Django 6.0.6 on 2026-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_alter_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='NEW', max_length=16),
        ),
    ]
