# Generated by Django 6.0.6 on 2026-06-11 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_remove_bid_is_accepted_bid_status'),
        ('projects', '0007_alter_project_max_price_alter_project_min_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('project', 'freelancer'), name='bid_project_freelancer_unique'),
        ),
    ]
