# Generated by Django 6.0.6 on 2026-06-14 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_bid_bid_project_freelancer_unique'),
        ('projects', '0008_remove_project_projects_pr_min_pri_155532_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], db_index=True, default='NEW', max_length=16),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status'], name='bids_bid_status_071bbe_idx'),
        ),
    ]
